In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/DataAnalyst.csv')
df.head(10)

,Unnamed: 0,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
5,5,Data Analyst,$37K-$66K (Glassdoor est.),3.9,Point72\n3.9,"New York, NY","Stamford, CT",1001 to 5000 employees,2014,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1,-1
6,6,Business/Data Analyst (FP&A),$37K-$66K (Glassdoor est.),4.4,Two Sigma\n4.4,"New York, NY","New York, NY",1001 to 5000 employees,2001,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1,-1
7,7,Data Science Analyst,$37K-$66K (Glassdoor est.),3.7,GNY Insurance Companies\n3.7,"New York, NY","New York, NY",201 to 500 employees,1914,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),"Travelers, Chubb, Crum & Forster",True
8,8,Data Analyst,$37K-$66K (Glassdoor est.),4.0,DMGT\n4.0,"New York, NY","London, United Kingdom",5001 to 10000 employees,1896,Company - Public,Venture Capital & Private Equity,Finance,$1 to $2 billion (USD),"Thomson Reuters, Hearst, Pearson",-1
9,9,"Data Analyst, Merchant Health",$37K-$66K (Glassdoor est.),4.4,Riskified\n4.4,"New York, NY","New York, NY",501 to 1000 employees,2013,Company - Private,Research & Development,Business Services,Unknown / Non-Applicable,"Signifyd, Forter",-1

In [3]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1

In [5]:
df.shape

(2253, 14)

### Data Cleaning
* Salary Parsing
* Company Name (text only)
* State field
* Age of Company
* Parsing of Job Description

In [6]:
# Removing Missing Values Of Salary Estimates (-1, if salary is not given insted of NaN)
df = df[df['Salary Estimate'] != '-1']

In [7]:
df.shape

(2252, 14)

Okhay! We have only 1 missing value. Let's move on!!

Now we have to remove `$` , `K` & `(Glassdoor est.)`. Here I have created a general concept to do this.

In [8]:
# string = '$200K-$520K (Glassdoor est.)'
# new_str = string.split('(')[0].replace('$', '').replace('K', '').lower().replace('employer provided salary', '').replace('per hour', '').split('-')
# lowerValue, upperValue = int(new_str[0]), int(new_str[1])
# averageSalary = (lowerValue + upperValue)/2
# print(averageSalary)

In [9]:
def salaryCleaner(object):
    string1 = object.split('(')[0].replace('$', '').replace('K', '').split('-')
    averageSalary = (int(string1[0]) + int(string1[1]))/2
    return averageSalary


salaryCleaner('200-220 (Glassdoor est.)')

210.0

In [10]:
df['Average Salary'] = df['Salary Estimate'].apply(lambda x: salaryCleaner(x))

/tmp/ipykernel_4199/4263636054.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Average Salary'] = df['Salary Estimate'].apply(lambda x: salaryCleaner(x))

In [11]:
df.head(120)

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Data Analyst,$51K-$87K (Glassdoor est.),3.8,Capgemini\n3.8,"Jersey City, NJ","Paris, France",10000+ employees,1967,Company - Public,Enterprise Software & Network Solutions,Information Technology,$10+ billion (USD),"Accenture, CGI, Sopra Steria",-1,69.0
116,ERP Data Analyst,$51K-$87K (Glassdoor est.),3.4,Wildlife Conservation Society\n3.4,"New York, NY","Bronx, NY",1001 to 5000 employees,1895,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,-1,69.0
117,Data Analyst,$51K-$87K (Glassdoor est.),3.6,Asembia\n3.6,"Florham Park, NJ","Florham Park, NJ",501 to 1000 employees,2004,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$5 to $10 million (USD),-1,-1,69.0
118,Healthcare Data/Reporting Analyst,$51K-$87K (Glassdoor est.),-1.0,Vesta Healthcare,"New York, NY","New York, NY",1 to 50 employees,2018,Company - Private,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,-1,69.0
119,PBM Data Analyst,$51K-$87K (Glassdoor est.),3.2,1199SEIU Funds\n3.2,"New York, NY","New York, NY",1001 to 5000 employees,-1,Nonprofit Organization,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,-1,69.0

So we cleaned `Salary Estimate`. Next we'll clean `Company Name`. We need to extract only company name from this column. Let's do it

In [12]:
x = 'HUL\n4.3'
y = x.split('\n')[0]
print(y)

HUL

In [13]:
df['Compant Text'] = df.apply(lambda x: x['Company Name'] if x['Rating'] < 0 else x['Company Name'].split('\n')[0], axis=1)

/tmp/ipykernel_4199/3536221676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Compant Text'] = df.apply(lambda x: x['Company Name'] if x['Rating'] < 0 else x['Company Name'].split('\n')[0], axis=1)

In [14]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc."
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,91.0,Spiceorb
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health

Well Done Mr. Coder!! It's time for your next challenge. Extract `State` Code from `Location` column.

In [15]:
df['Job State'] = df['Location'].apply(lambda x: x.split(',')[1])

/tmp/ipykernel_4199/2474640439.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Job State'] = df['Location'].apply(lambda x: x.split(',')[1])

In [16]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc.",CO
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics,CO
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,91.0,Spiceorb,CO
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services,CO
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health,CO

As expected, you did it. Perform your next task Coder! Find how old the company is ?

In [17]:
df['Company Age'] = df.Founded.apply(lambda x: (2022 - x) if x!= -1 else -1)

/tmp/ipykernel_4199/2809517137.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company Age'] = df.Founded.apply(lambda x: (2022 - x) if x!= -1 else -1)

In [18]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State,Company Age
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY,61
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY,129
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY,19
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY,20
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2248,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc.",CO,-1
2249,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics,CO,87
2250,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,91.0,Spiceorb,CO,-1
2251,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services,CO,38
2252,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health,CO,158

In [19]:
df.to_csv('Cleaned_DataAnalyst.csv', index=False)

In [20]:
df2 = pd.read_csv('data/Cleaned_DataAnalyst.csv')

In [21]:
df2

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State,Company Age
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY,61
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY,129
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY,19
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY,20
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc.",CO,-1
2248,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics,CO,87
2249,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,91.0,Spiceorb,CO,-1
2250,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services,CO,38
2251,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health,CO,158

Its time to do some `Exploratory Data Analysis (EDA)`. So let's dive into it

In [22]:
# this is our cleaned dataset stored in variable df2
df2.head()

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State,Company Age
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY,61
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY,129
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY,19
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY,20
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY,13

In [23]:
df2['Job Title'].value_counts()

Data Analyst                        405
Senior Data Analyst                  90
Junior Data Analyst                  30
Business Data Analyst                28
Sr. Data Analyst                     21
                                   ...
Data Analyst – Level II               1
Data Analyst/Programmer               1
Data Services Business Analyst 2      1
Call Center Data Analyst              1
Senior Quality Data Analyst           1
Name: Job Title, Length: 1271, dtype: int64

In [45]:
df3 = df2.copy()

In [66]:
def jobTitleCleaner(object):
    job = object
    if 'data' in job.lower()and 'analyst' in job.lower():
        return 'Data Analyst'

def jobPositionCleaner(object):
    job = object
    if 'senior' in job.lower():
        return 'Senior'
    elif 'junior' in job.lower():
        return 'Junior'
    elif 'entry level' in job.lower() or 'intern' in job.lower():
        return 'Intern'
    else:
        return 'Na'

jobPositionCleaner('Data Business analyst')

'Na'

In [67]:
df3['Profession'] = df3['Job Title'].apply(lambda x: 'Data Analyst' if 'data' and 'analyst' in x.lower() else x)

In [68]:
df3['Profession'].value_counts()

Data Analyst    2252
Name: Profession, dtype: int64

In [69]:
df3['Job Position'] = df3['Job Title'].apply(jobPositionCleaner)

In [70]:
df3

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State,Company Age,Profession,Job Position
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY,61,Data Analyst,Na
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY,129,Data Analyst,Na
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY,19,Data Analyst,Senior
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY,20,Data Analyst,Na
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY,13,Data Analyst,Na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc.",CO,-1,Data Analyst,Na
2248,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics,CO,87,Data Analyst,Senior
2249,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1,91.0,Spiceorb,CO,-1,Data Analyst,Na
2250,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services,CO,38,Data Analyst,Na
2251,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health,CO,158,Data Analyst,Senior

In [71]:
df3['Job Position'].value_counts()

Na        1889
Senior     285
Junior      60
Intern      18
Name: Job Position, dtype: int64

In [84]:
df3['Job State'] = df3['Job State'].apply(lambda x: x.strip() if x.strip().lower() != 'arapahoe' else 'CO')

In [86]:
df3['Job State'].value_counts()

CA    626
TX    394
NY    345
IL    164
PA    114
AZ     97
CO     96
NC     90
NJ     86
WA     53
VA     48
OH     35
UT     33
FL     27
IN     23
DE     11
GA      4
SC      3
KS      3
Name: Job State, dtype: int64

In [128]:
def competitorsCount(object):
    if object == '-1':
        return 0
    else:
        x = object.split(',')
        count = len(x)
        return int(count)

competitorsCount('HUL, Dabur')

2

In [123]:
df3['Competitors Count'] = df3['Competitors'].apply(competitorsCount)

In [124]:
df3

,Job Title,Salary Estimate,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,...,Revenue,Competitors,Easy Apply,Average Salary,Compant Text,Job State,Company Age,Profession,Job Position,Competitors Count
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,...,$100 to $500 million (USD),-1,True,51.5,Vera Institute of Justice,NY,61,Data Analyst,Na,0
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,...,$2 to $5 billion (USD),-1,-1,51.5,Visiting Nurse Service of New York,NY,129,Data Analyst,Na,0
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,...,Unknown / Non-Applicable,GoDaddy,-1,51.5,Squarespace,NY,19,Data Analyst,Senior,1
3,Data Analyst,$37K-$66K (Glassdoor est.),4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,...,$50 to $100 million (USD),-1,-1,51.5,Celerity,NY,20,Data Analyst,Na,0
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,...,$100 to $500 million (USD),DraftKings,True,51.5,FanDuel,NY,13,Data Analyst,Na,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,...,Unknown / Non-Applicable,-1,-1,91.0,"Avacend, Inc.",CO,-1,Data Analyst,Na,0
2248,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,...,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1,91.0,Arrow Electronics,CO,87,Data Analyst,Senior,3
2249,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,...,-1,-1,-1,91.0,Spiceorb,CO,-1,Data Analyst,Na,0
2250,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,...,$25 to $50 million (USD),-1,-1,91.0,Contingent Network Services,CO,38,Data Analyst,Na,0
2251,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,...,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1,91.0,SCL Health,CO,158,Data Analyst,Senior,3